services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-container
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    command: start --tunnel

  postgres:
    image: postgres:15-alpine
    container_name: n8n-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped



volumes:
  postgres_data:
  n8n_data: